name: CI

on:
  pull_request:
    branches:
      - main
      - preview

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # precisa vir antes do setup-node para o cache "pnpm" funcionar
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm exec tsc --noEmit

      - name: Run ESLint
        run: pnpm lint

      - name: Build project
        run: pnpm build
        env:
          NEXT_PUBLIC_API_URL: http://localhost:3000
